### ISSUE TITLE
bug:  Database sequences: Resetting...

### ISSUE THREAD

**Issue by brennofaneco** [snaplet/docs-old#130]
Hey, every time that I restore my database, I have the following output, (note this resetting, never stops), is that correct?

```
✔ Table data: Imported
✔ Vacuum: Done
[Sequences] Warning: column "sortweight" does not exist
Wrote restore.log (​file:///Users/dev/review/app/.snaplet/snapshots/1670247744843-feed-calculate/restore.log​)

🎉 Snapshot restored
⠧ Database sequences: Resetting...
```

**Comment by peterp** [comment]
Hey @brennofaneco! Wanted to apologize for not getting back to you sooner. I didn't see this issue here. Could you reach out to us on Discord via https://app.snaplet.dev/chat, so that we can try and help you?
