### ISSUE TITLE
Can't install CLI on Windows

### ISSUE THREAD

**Issue by lack-of-gravitas** [snaplet/docs-old#33]
Running curl on windows (in elevated Terminal) dumps the following message... 

curl -sL https://app.snaplet.dev/get-cli/ | bash

-bash: line 1: $'\r': command not found
: invalid optionet: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
-bash: line 4: $'\r': command not found
-bash: line 6: $'\r': command not found
-bash: line 12: $'\r': command not found
-bash: line 15: $'\r': command not found
-bash: line 67: syntax error near unexpected token `$'{\r''
'bash: line 67: `cleanup() {

**Comment by lack-of-gravitas** [comment]
No response since April... repo seems abandoned. Closing as no longer pursuing this tool.

**Comment by peterp** [comment]
@lack-of-gravitas Sorry about that. I've just re-opened this, I don't know why this wasn't on my radar. I'll get someone to take a look at this right now. @ewaldsnaplet @CarelFdeWaal Do either of you perhaps have a Windows machine?

**Comment by ewaldsnaplet** [comment]
> @lack-of-gravitas Sorry about that. I've just re-opened this, I don't know why this wasn't on my radar. I'll get someone to take a look at this right now. @ewaldsnaplet @CarelFdeWaal Do either of you perhaps have a Windows machine?

No sorry @peterp, but I believe @jgoux has an up-to-date machine that we could test on.

**Comment by dave-v** [comment]
For anyone else with this problem, I was able to get round it by downloading the Windows binary directly, which you can see by looking at the script:
https://snaplet-public.s3-accelerate.amazonaws.com/cli/beta/snaplet-win-0.20.1.exe
Rename the file to `snaplet`, put it on your PATH, and you should be good to go.

**Comment by dave-v** [comment]
Also, trying to upgrade in Git Bash on Windows:
```bash
$ snaplet upgrade
Installing Snaplet CLI 0.21.0...
error fetching 'https://webinstall.dev/api/installers/pathman.sh?formats=tar,exe,zip,xz,git,dmg'
```
In Command Prompt, it does something a bit weird (which I cannot get to work, but that could be my due to my ignorance with WSL):
```cmd
snaplet upgrade
Installing Snaplet CLI 0.21.0...
Downloading https://snaplet-public.s3-accelerate.amazonaws.com/cli/beta/snaplet-linux-0.21.0...
######################################################################## 100.0%
... Done. Installed at: /root/.local/bin/snaplet
Please reload your shell to refresh your PATH and start using snaplet
```

**Comment by peterp** [comment]
We've now got an NPM installer available, check it out: https://www.npmjs.com/package/snaplet

This should work in Windows. Let me know if you're still experiencing this problem.
