### ISSUE TITLE
"Edit this page" is broken in some pages

### ISSUE THREAD

**Issue by zomars** [snaplet/docs-old#47]
From: https://docs.snaplet.dev/tutorials/github-actions/

Clicking "edit this page"

![image](https://user-images.githubusercontent.com/3504472/177834784-29cd3985-adaa-4506-85db-fbbb5ce6f94e.png)

Sends here:

https://github.com/snaplet/docs/docs/06-tutorials/github-actions.md

Which returns a 404

**Comment by zomars** [comment]
AFAIK the correct url should be:

https://github.com/snaplet/docs/blob/main/docs/06-tutorials/github-actions.md

**Comment by peterp** [comment]
Weird! I'll try and figure this out.

**Comment by peterp** [comment]
Fixed!
