### ISSUE TITLE
Consider adding a webi compatible installer

### ISSUE THREAD

**Issue by zomars** [snaplet/docs-old#79]
As requested [here](https://github.com/webinstall/webi-installers/issues/455) this would simplify a lot installing snaplet in non-sudo environments like Vercel CI.

**Comment by peterp** [comment]
This is a great idea, thanks @zomars

**Comment by peterp** [comment]
@zomars We're not 100% there yet, but we don't require `sudo` anymore, and we'll publish a `@snaplet/cli` package soon!

**Comment by peterp** [comment]
We've not entirely webi, but we no longer require sudo. Closing this for now.
